name: Frontend Build and Push

on:
  pull_request:
    paths:
      - "frontend/**"
      - ".github/workflows/frontend-build.yml"
      - ".github/workflows/reusable-sign-container-images.yml"
    types:
      - opened
      - closed
      - synchronize

permissions:
  contents: read
  packages: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  IS_MONOREPO: true
  FRONTEND_PATH: frontend
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/nachet-frontend

defaults:
  run:
    working-directory: frontend

jobs:
  get-version:
    uses: ./.github/workflows/reusable-frontend-versions.yml
    with:
      working-directory: frontend
      package-name: nachet-frontend
      skip-version-check: false

  build-and-push-gcr:
    needs: get-version
    # uses: ./.github/workflows/workflow-build-push-container-github-registry-mono.yml
    uses: ai-cfia/github-workflows/.github/workflows/workflow-build-push-container-github-registry-mono.yml@main
    with:
      working-directory: frontend
      container-name: ${{ github.event.repository.name }}-frontend
      tag: ${{ github.sha }}
      release-version: ${{ needs.get-version.outputs.app-version }}
      registry: ghcr.io/ai-cfia
    secrets: inherit

  sign-images:
    needs: [get-version, build-and-push-gcr]
    permissions:
      contents: read
      packages: write
      id-token: write
    uses: ./.github/workflows/reusable-sign-container-images.yml
    with:
      image-name: ghcr.io/ai-cfia/${{ github.event.repository.name }}-frontend
      image-label: frontend
      release-version: ${{ needs.get-version.outputs.app-version }}
    secrets: inherit
